### ISSUE TITLE
Has the project been abandoned?

### ISSUE THREAD

**Issue by Akimotorakiyu** [LowwwLtd/shadertoy.js#1]

**Comment by andrevenancio** [comment]
Hi @SilverLeaves mmmm Its not abandon, but I haven't commit any code to this in ages.

I'm currently working on an different concept, its still a private repo. will share it in the next couple of months.

Just to be clear, I'm not associated with https://shadertoy.com  in any way.

This is only a repo I've created because I wanted to share my shadertoy experiments on my website. So it kind of follows their API and shader structure. Up until they updated to WebGL2.0 where there are some minor semantics on the GLSL ES 3.0 things like `texture2d` become `texture` etc.

Let me know what you're looking for, I might be able to point you in the right direction.
